[package]
name = "epicboxlib"
version = "1.0.1"
authors = ["vault713 devs"]
description = "A library that encapsulates epicbox integration."
keywords = [ "epicbox", "vault713", "epic", "mimblewimble", "rust", "crypto", "cryptocurrency", "wallet713" ]
license = "Apache-2.0"
readme = "README.md"
edition = "2021"

[dependencies]
thiserror = "1"
colored = "1.7"
failure = "0.1"
log = "0.4"
parking_lot = {version = "0.6"}
rand = "0.5"
regex = "1"
ring = "0.16.20"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sha2 = "0.7"
ws = { version="0.9.2" }

grin_secp256k1zkp = { version = "0.7.4", features = ["bullet-proof-sizing"]}

epic_core     = { git = "https://github.com/EpicCash/epic", branch = "master" }
epic_wallet_libwallet = { git = "https://github.com/EpicCash/epic-wallet" , branch = "master" }
